Core:
  InsertNum: 100000

Log:
  ServiceName: core
  Mode: file
  Path: logs
  Level: debug
  Encoding: json
  KeepDays: 7

Gorm:
  TablePrefix: "mb_"
  Debug: true
  MaxLifetime: 7200
  MaxOpenConns: 150
  MaxIdleConns: 50

MySQL:
  Host: 192.168.0.170
  Port: 3306
  User: root
  Password: donson.123
  Database: draning
  Parameters: "charset=utf8mb4&parseTime=True&loc=Local"

ClickHouse:
  Host: 192.168.0.171
  Port: 9000
  User: default
  Password: donson.123
  Database: draning_ck
  ReadTimeout: 30
  WriteTimeout: 30

Tables:
  - Name: "mb_opr_account"
    Skip: true
    Full: true
    Engine: "ReplacingMergeTree"
    Partition: ""  # Table create partitioning by, like toYYYYMM(created_at).
    Order: "id" # , 分割
    Where: ""
    Insert: true
    Rename: ""
  - Name: "mb_opr_customer"
    Skip: false
    Full: true
    Engine: "ReplacingMergeTree"
    Partition: ""  # Table create partitioning by, like toYYYYMM(created_at).
    Order: "id" # , 分割
    Where: ""
    Insert: true
    Rename: ""
