// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package node

import (
	"context"
	"fmt"
	"github.com/littlerivercc/go-sync/internal/logic"
	"github.com/littlerivercc/go-sync/internal/svc"
)

type Server struct {
	svcCtx *svc.ServiceContext
}

func NewServer(svcCtx *svc.ServiceContext) *Server {
	return &Server{
		svcCtx: svcCtx,
	}
}

func (s *Server) Run(ctx context.Context, tables []string) error {
	fmt.Println(s.svcCtx.Config.Tables)
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Run(tables)
}
